### ISSUE TITLE
LDAP Login

### ISSUE THREAD

**Issue by MatthiasGer0821** [edgarrmondragon/citric#139]
* Citric version: 0.0.5
* Python version: 3.9
* Operating System: Debian 11

###
I tried to login to the activated RemoteControl API and received the error saying the internal database authentification is not allowed for this user. 
This makes sense, since I am trying to login via LDAP. 

My question is:
Is it possible to use citric for LDAP acess to the API?

Best regards, 
Matt

**Comment by edgarrmondragon** [comment]
Hi @MatthiasGer0821! I completely overlooked this use case since I've never used LDAP with LimeSurvey.

I'm a correct in assuming that you'd be using the [`AuthLDAP` plugin](https://manual.limesurvey.org/Authentication_plugins#LDAP), or any similar plugin for that matter?

In that case, according to [the RC docs](https://api.limesurvey.org/classes/remotecontrol_handle.html#method_get_session_key) I think I can update the `Client` signature to include an optional `plugin` argument like:

```python
with Client(
    "https://mylimeserver.com/index.php/admin/remotecontrol",
    "iamadmin",
    "secret",
    plugin="AuthLDAP",
) as client:'
...
```

**Comment by edgarrmondragon** [comment]
WIP PR: [#140](https://github.com/edgarrmondragon/citric/pull/140)

**Comment by MatthiasGer0821** [comment]
Hi @edgarrmondragon, thank you for your response! Yes, i´d use the AuthLDAP plugin. Thank you for implementing this. 
That´s a huge help. 
Best regards,
Matt

**Comment by edgarrmondragon** [comment]
Hey @MatthiasGer0821, I just cut a `0.0.6` release with the feature described here: https://citric.readthedocs.io/en/latest/#use-a-different-authentication-plugin.

Let me know if that allows to use LDAP login 🙂

**Comment by MatthiasGer0821** [comment]
Hi @edgarrmondragon. 

Thanks so much! I tested it quite a bit and finally got it working!
The problem was that i received an error "invalid settings". I did some digging and found that I need to be superadmin to get the site settings, specifically RPCInterface.

But for my use case (i.e., not being super admin) i had to adjust the code:
In session.py, i had to comment out the following lines.
        #if self.get_site_settings("RPCInterface") != "json":
        #    raise LimeSurveyError("JSON RPC interface is not enabled.")
and then everything worked. 

I got it after reading this: https://github.com/LimeSurvey/LimeSurvey/blob/master/application/helpers/remotecontrol/remotecontrol_handle.php#L100

I am not sure if my use case is super rare, I use limesurvey at the university i am working, and apparently it´s not possible to become superadmin, but they can enable the RC API.

**Comment by edgarrmondragon** [comment]
Thanks for confirming and thank you for the ko-fi @MatthiasGer0821! 😄 

You're right about the new issue. It seems like users without `Superadmin` permission can't call the [`get_site_settings` RPC method](https://api.limesurvey.org/classes/remotecontrol_handle.html#method_get_site_settings). I created https://github.com/edgarrmondragon/citric/issues/142 to track that. The fix should as simple as removing that check. The `get_session_key` would fail before that anyway.

**Comment by edgarrmondragon** [comment]
I just cut `0.0.7` with that fix 🙂
