### ISSUE TITLE
[Bug]: <using citric with google colab

### ISSUE THREAD

**Issue by AmauryVanEspen** [edgarrmondragon/citric#729]
### Citric Version

0.1.0

### Python Version

3.9

### LimeSurvey Version

5.3.19

### Operating System

Google Colab - Linux

### Description

Not able to run the sample script in google colab

### Code

```python
from citric import Client

with Client(
    "https://mylimesite.limequery.com/admin/remotecontrol",
    "myusername",
    "mypassword",
) as client
    for survey in client.list_surveys():
        print(survey["surveyls_title"])

does not run in google colab
```

**Comment by AmauryVanEspen** [comment]
Hello,
the sample does not run in google colab

File ["<ipython-input-41-bbd532bbf563>"](https://localhost:8080/#), line 7
    ) as client
               ^
SyntaxError: invalid syntax

could you please provide insights ?

Thank you
Amaury

**Comment by edgarrmondragon** [comment]
Hi @AmauryVanEspen! I just realized the very first sample is missing a colon 🤦

This should work

```python
from citric import Client

with Client(
    "https://mylimesite.limequery.com/admin/remotecontrol",
    "myusername",
    "mypassword",
) as client:  # <-- this colon was missing
    for survey in client.list_surveys():
        print(survey["surveyls_title"])
```

**Comment by AmauryVanEspen** [comment]
Hello
Still have an issue that i do not understand,
i've install citric with !pip install citric,
however, still an issue with the main function
`---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[<ipython-input-4-36d407b365c2>](https://localhost:8080/#) in <module>
      1 from citric import Client
      2 
----> 3 with Client(
      4     "http://aredil.freeboxos.fr:8036/index.php/admin/remotecontrol",
      5     "api",

8 frames
[/usr/lib/python3.8/json/decoder.py](https://localhost:8080/#) in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by edgarrmondragon** [comment]
@AmauryVanEspen can you confirm that the JSON RPC is enabled in the [global settings](https://manual.limesurvey.org/Global_settings#Interfaces)?

**Comment by AmauryVanEspen** [comment]
Hello @edgarrmondragon ,
thank you, right now it's working, there was a server unavailability,
also, i've seen the page [https://citric.readthedocs.io/en/latest/index.html](https://citric.readthedocs.io/en/latest/index.html) has been updated with the semi colon,
thank you for quick support and reply !
now, digging the API =) !

**Comment by edgarrmondragon** [comment]
That's great news @AmauryVanEspen!

Let me know if you run into any other issues 😊

**Comment by AmauryVanEspen** [comment]
Thank you @edgarrmondragon 
i would be curious to discuss a bit with you about usage of the API you did usually and maybe share some best practices and accelerators in python, there are maybe some useful buidling block to reuse together
